name:                oscompiler
version:             0.1.0.0
github:              "jpittis/olimpico-scheme/oscompiler"
author:              "Jake Pittis"
maintainer:          "jakepittis@gmail.com"
copyright:           "2019 Jake Pittis"

description:         A compiler for Olimpico Scheme.

dependencies:
- base >= 4.7 && < 5
- megaparsec
- mtl
- text
- hspec
- directory
- HUnit

library:
  source-dirs: src

executables:
  oscompiler-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - oscompiler

tests:
  oscompiler-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - oscompiler
